// src/pages/Home.jsx
import { Container, Row, Col } from "react-bootstrap";

const RefundPolicy = () => {
  return (
    <div className="service-info-section">
      <header className="contact-header text-center ">
        <h1 className="header-title">
          Refund Policy
        </h1>
      </header>
      <Container>
        <Row>
          <Col md={12}>
            <div className="service-content text-justify">
              <p>Xcel Global Services will not, under any circumstances, issue refunds for early service withdrawal.</p>
<ol>
	<li>The refund percentages mentioned are for the full-service fee paid and not only for the amount paid. Refund percentages are applicable only if the complete fee of the product is paid without any balance. Clients would not be eligible for the refund percentage even if they fall in one of the mentioned clauses or if they haven&rsquo;t paid the complete full-service fee mentioned.</li>
	<li>The immigration pronouncements at times are discounted on the basis of future expectations and clients are registered in advance, that is, before the actual qualification is announced to make sure that the cap system is met. It&rsquo;s pre-agreed that the client does acknowledge this and is ready to do so to cut the last-minute rush and get ready as per all requirements by the time the immigration authorities announce them. If the client&rsquo;s profile is not eligible after the announcement, client can choose to transfer to other opportunities.</li>
	<li>Xcel Global Services has a zero-tolerance policy for charge backs. Any customer who disputes a credit card payment that is found to be valid will be permanently blacklisted and barred from use of the service. Any past due fees and costs will be sent to collections. If our collection efforts fail, unpaid debts will be reported to all available Credit Reporting Agencies.</li>
	<li>The client understands and agrees that the total invoice amount (bill value) will include the Xcel Global Services consultation fee and the applicable tax. However, the refund would be calculated only on the Xcel Global Services consultation fee. The tax component is non-refundable at any stage.</li>
	<li>In case of rejection by the Immigration Authorities, Xcel Global Services will refund the applicable amount as per stated in the agreement. The refund will be made within 15-30 working days after the client fills the Online Refund Claim Form to Xcel Global Services. The client has to enclose a copy of the letter of rejection from the Authority to support the Refund Claim. If a client fails to enclose a copy of the rejection letter or rejection stamp on the client&rsquo;s passport, Xcel Global Services will not be able to give a refund.</li>
	<li>The company is not responsible for any delay caused by third-party services. Also, clients cannot claim a refund of service charges.</li>
	<li>Xcel Global Services is not responsible for refund of any fees or other amounts/charges that have been paid to any Assessing Bodies, Immigration Authorities, Embassy/Consulate/High Commission in the event of the client not getting approval of immigration, or in case of rejection or non-acceptance of his/her request at any stage by any respective authority. The fees only includes the charges towards the services rendered by Xcel Global Services and does not include any request or assessing fees. The client agrees to pay the entire additional fees, as applicable.</li>
	<li>If the client has paid the money through an online card service, the client hereby agrees that he/she will not withdraw, or is not entitled to charge back the amount, without the knowledge of Xcel Global Services, in case of payment made by any mode. This includes Razorpay Payment Gateway except otherwise following the norms of refund as mentioned in the agreement and the procedure prescribed by law prevailing at that time under the Jurisdiction of Hyderabad, State of Telangana.</li>
	<li>If the client has paid the money through Credit Card or Net Banking, he will undertake voluntarily that he will not dispute the payment or notify the designated bank for chargeback, insisting that the bank to withhold or cancel the payment made to Xcel Global Services by him. The client further undertakes to inform his banker that the payment made to Xcel Global Services is genuine and the transaction is an exception for his request to cancel or chargeback the payment in his favor. This includes misuse and card loss cases either by him or through anyone else. The client agrees to cooperate with Xcel Global Services in this aspect in case Xcel Global Services wishes to defend/represent the matter in their favor before any bank/authority.</li>
	<li>The Service Charges by Xcel Global Services have no reference to the market charges and are as per the company standards to which the client agreed. Any claims after the registration, like charges being too expensive and such, would not be entertained and the client would have no right to contest the same as it was explained and expressed through all the sources of information, and the client has been informed before registering.</li>
	<li>The client accepts that immigration includes showing enough funds, if applicable, which differs from country to country and the pathway/category the client applies. The client undertakes to meet such requirement as desired by the concerned immigration/other authorities, and failure to provide such funds by the client shall not make Xcel Global Services liable for any refund of the service charges or part thereof. In such cases, no refund request for service charges will be entertained.</li>
	<li>The client also accepts that all/any registrations for any countries before this client declaration agreement date, if any, with Xcel Global Services would be nullified, and no claim of the service or the fee can be claimed until it is given in writing by Xcel Global Services.</li>
	<li>In case of the permit being rejected on the following grounds no refund will be made &ndash;
	<ul>
		<li>If the client fails to attend the interview.</li>
		<li>Failure of medicals by the client or his or her family members included in the request.</li>
		<li>If the client does not comply with the requirements of the Embassy or the Consulate.</li>
		<li>Failure to provide a genuine Police Clearance Certificate, which is not less than 3 months old</li>
		<li>Failure to prove sufficient funds for settlement by the client or his or her family members.</li>
		<li>Prior violation of any immigration law by the client or any of his or her family members.</li>
		<li>Late submission of any additional papers requested by the consulate at a later date</li>
		<li>The client fails to get the required score in English language test to meet the eligibility criteria and as advised by the Xcel Global Services consultant.</li>
		<li>There would be no refund if the client abandons his/her case within 3 months from the date of registration</li>
		<li>Non-communication with your Consultant for a period of 3 months shall also be deemed to be abandonment</li>
	</ul>
	</li>
	<li>The fee paid to authorities or any other institution is the liability of the client and is not included in the service charges. Xcel Global Services will not entertain any claim of refund in case of rejection.</li>
	<li>The client must offer, inside 30 days, each and every paper, forms, and facts that will make it possible for Xcel Global Services to work on his/her request and make it submit-ready before the appropriate assessing/immigration authority. The client&rsquo;s inability to do the same will only suggest that no reimbursement of the advisory/consulting fee offered to Xcel Global Services is outstanding.</li>
	<li>The client should notify Xcel Global Services of each and every communication received by him/her from the office &ndash; in writing or via phone &ndash; inside a week of the receiving of such a message. Besides, the client shall notify the said immigration consultancy of each and every communication (in written form or through phone) undertaken by the client, straight with the involved bureau inside a week or 7 days of such a contact. This comprises personal visits made to the office, and/or inquiry made via phone. The client&rsquo;s inability to do the same will only suggest that no money back whatsoever is outstanding of any secretarial charges offered to Xcel Global Services.</li>
	<li>The client will participate in each and every interview, as and when needed by the concerned agency, at the place mentioned by the agency, and at his own cost, and swiftly follow each and every given order as given by the agency. The client&rsquo;s inability to do the same will only suggest that no refund whatsoever is outstanding of any secretarial charges offered to Xcel Global Services.</li>
	<li>If the request/petition is returned/rejected/delayed owing to an error in the request fee or mode of payment, the client agrees not to contest on withdrawal of his request on this ground; as the payment and the mode of the payment of request fee is the sole liability of the client.</li>
	<li>It is understood that submission of a request for immigration is never generic, routine and/or time bound. The concerned case officer may call for additional papers, as per the changing requirements of the procedure, and may request for further submission of such additional papers to the concerned immigration authorities. Any request for the refund on these grounds will not be entertained.</li>
	<li>The client should also understand and accept that no refund or transfer of Xcel Global Services fee to a friend or a relative will be done in the event he or she abandons his/her request or decides to opt out due to any reason during the proceedings after he/she signs-up.</li>
	<li>The client will offer every needed information and papers, such as the English translations, in an agreed form as sought by Xcel Global Services and the involved office. It has been fully agreed upon by the said immigration consultancy on the ground of the facts and papers presented by the client. In case the furnished details are discovered to be inaccurate or fake or deficient or incorrect, the offer will not be entertained by the concerned Immigration authorities. Moreover, the immigration consultancy takes no responsibility whatsoever for negative impact on the result of the petition and the ensuing rejection on this basis. No refund shall be claimed, either of the consulting charge or the amount paid to the government organizations, under such situations.</li>
	<li>Xcel Global Services has the right to terminate/withdraw their services without refund of service fee of the client on below terms.
	<ul>
		<li>If the client does not submit all papers within the stipulated time from the date of his/her registration which is normally within one month</li>
		<li>Tries to malign the name of the company in whatsoever manner, which tampers the functioning of the business or reputation</li>
		<li>Doesn&rsquo;t respond to the mails and calls made by the company for more than a month and backs out due to personal reasons</li>
		<li>Xcel Global Services reasonably forms the view that someone other than the client is attempting to gain access to the Service for his or her personal benefit.</li>
		<li>At the discretion of Xcel Global Services, you behave in such a way that renders your consultant unable to provide the service(s) any longer.</li>
	</ul>
	</li>
	<li>The client herewith agrees to meet all the requirements of the concerned authorities who conduct an assessment or decide on outcome. The client also agrees to submit all the papers including originals if required by the concerned assessing authorities. The client understands that any failure on his/her part to submit these papers or part thereof is an independent failure of client and Xcel Global Services is in no way responsible for the same. Hence, the client agrees that failure to produce papers cannot be a valid reason to claim a refund.</li>
	<li>The client will settle all charges which may be owed to a variety of government and skills appraisal bodies and language testing organizations such as but not restricted to the skills appraisal costs, residency permit petition costs, the Acceptable English language or other language tests if applicable, health tests, etc. The given charges are strictly non-refundable and not adjustable by either any of the receiving offices or the immigration consultancy, notwithstanding the final conclusion on the petition. A favorable appraisal or conclusion is the sole prerogative of the involved organization, even as the immigration consultancy exercises no control at all over the final outcome at any phase of the petition. Xcel Global Services has given no assurance whatever of a favorable appraisal or end result of the projected petition of the client in any phase.</li>
	<li>The client will inform Xcel Global Services about every news involving a change of housing/mailing address, educational/specialized credentials, change of matrimonial status/service or company, newly born kids or any police/unlawful case after the submission of the petition and while the proceeding is going on till the time of the discharge of Permanent Residence Permit. The client&rsquo;s inability to do the same will only show that no refund at all is outstanding of any advisory charges given to the immigration consultancy.</li>
</ol>
<p>&nbsp;</p>
<ol>
	<li>The client will appear for an Acceptable English language or other language test as applicable and achieve a minimum individual total of the group in every given four appraisal factors &ndash; Listening, Reading, Writing, and Speaking &ndash; as appropriate for him/her and as per the requirement of the issuing authority/assessment body. The client thoroughly realizes and concurs that his petition cannot be submitted without the necessary Acceptable English language or other language tests (if applicable), including for partner or dependents above 18 years, and no reimbursement of the advisory/consulting/secretarial services charge offered to Xcel Global Services will be outstanding or settled in a situation wherein he fails to attain the required Acceptable English language or other language test.</li>
	<li>The client shall also make certain that he/she is married or in any relationship which is acceptable to be considered as dependent&ndash;spouse or the acceptable dependent/s appears for an Acceptable English language or other language tests if applicable and offers a report with minimum score as is appropriate on the basis of the decided SERVICE LEVEL AGREEMENT with Xcel Global Services.</li>
	<li>By signing/acknowledging the agreement to avail our services, the client cannot withdraw AT ANY POINT during the procedure because of their own personal circumstances which might have changed. It is unacceptable to consider or entertain any form of settlement. As a business with heavy investment, we cannot accommodate requests for refunds once services have been provided for or when any part of the procedure has commenced.</li>
	<li>The secretarial charges given to Xcel Global Services does not comprise any amount owed to any Governmental organization, and to any language testing group or for any other reason, and shall be restricted to the services and duties of the consultancy as duly set and decided under the SERVICE LEVEL AGREEMENT inked separately with the client.</li>
	<li>The client will confirm to Xcel Global Services in case he/she is keen to use the alternative services of a global authorized assignee (Embassy/Consulate/Language test conducting centers, health check conducting centers, etc.) and also make additional payments for such services to Xcel Global Services, as duly arranged and decided under the SERVICE LEVEL AGREEMENT inked separately with the client. Any online payment will not contain fees owed to such global authorized assignees (Embassy/Consulate/Language test conducting centers, health check conducting centers, etc.) and in each and every situation the fee will not be given back.</li>
	<li>The client clearly accepts that he has been apprised of the usual waiting durations/average time, as appropriate to his permit class, and further that such waiting durations/usual time solely depends on the convenience of the office/appraisal body concerned. The client also fully agrees and realizes that he will never have any claims whatsoever on any sort of refund of the charge made on or off-site, on the ground of the extended petition time periods.</li>
	<li>Xcel Global Services has not offered any sort of assurance, advice or pledge on work or job assurance, following an approval for the permit and after landing for any given overseas country. No compensation will be claimed of any advisory/consulting/secretarial service charges offered earlier to Xcel Global Services by the client on the ground that Xcel Global Services has been unable to offer a job guarantee abroad.</li>
	<li>In a situation wherein a clash/dispute in the matter of the payment made by a client to Xcel Global Services towards the SERVICE LEVEL AGREEMENT duly inked with Xcel Global Services. The responsibility of Xcel Global Services, in case it arises and is outstanding, either monetary or otherwise, shall not surpass, and will be restricted to the charges offered to Xcel Global Services as advisor/consulting/secretarial charges as part of the duly inked SERVICE LEVEL AGREEMENT.</li>
	<li>There are certain countries that have a cap system, and hence the approval of Green Card/Permanent Residence is subject to the cap not reached for that year. The client may have the required points as needed by the immigration authorities of the specified country, but he/she still may not get the Green Card/Permanent Residence if the cap has been reached for that year. Failing to get a Green Card/Permanent Residence because of the cap limit cannot be a reason for claiming a refund, and client fully understands the same.</li>
	<li>If your request for a refund falls under the acceptable terms and conditions of the Company and the service agreement, the time taken for such a request would be 15-30 working days.</li>
	<li>The service amount written is for the full service as on the date of registering, and only includes an individual&rsquo;s request. Any assumption of extended services to family or children is at the client&rsquo;s discretion, and the company will not be held responsible for these kinds of assumptions.</li>
	<li>The client shall loyally reveal before Xcel Global Services &ndash; each and every detail involving each and every, existing or past, case of wrong-doings and/or conviction, and insolvency leveled against the clients and those who are dependent on him. If he does not reveal such details, and if the same is found afterward, no refunds at all of the money given to Xcel Global Services in question will be made.</li>
	<li>Xcel Global Services is bound to maintain the confidentiality and privacy of a client. Accordingly, Xcel Global Services takes reasonable steps to protect personal information collected by Xcel Global Services from misuse and loss and from unauthorized access, modification or disclosure. Xcel Global Services may use and disclose the client&rsquo;s (and if applicable, the client&rsquo;s family&rsquo;s) personal information for the primary purpose for which it is collected, for reasonably expected secondary purposes which are related to the primary purpose and in other circumstances as authorized by the Privacy Act. In general, Xcel Global Services will disclose the client&rsquo;s personal information for the following purposes:</li>
</ol>
<ul>
	<li>To conduct our business,</li>
	<li>To provide and market our services,</li>
	<li>To communicate with the client,</li>
	<li>To comply with our legal obligations, and</li>
	<li>To help us manage and improve our services.</li>
</ul>
<p>&nbsp;</p>
<p>Any fees paid to Xcel Global Services are for the provision of services listed on Xcel Global Services website. Unless otherwise stated, all fees are quoted in Indian Rupees. You are responsible for paying all fees and applicable taxes associated with our services using one of our accepted payment methods.</p>
<p>Xcel Global Services is not a part of any government authority/organization or embassy. We are a Private Limited company and we do not have the authority to grant you a permit of any kind. We can only assist, guide and advise people who want to migrate or travel to their selected country. Please note that the final decision on all requests rests with the relevant government departments in their respective countries.</p>
<p>Our agreements with clients are drawn on the bedrock of trust, sincerity, and security, and each option is spelled out clearly. Our terms are transparent and there is nothing hidden.</p>
<p>The client agrees and acknowledges that the company doesn&rsquo;t suggest or force any service/product etc. and the pronouncement of a particular service/product etc. is the client&rsquo;s individual decision and cannot be at any time assumed to be a company judgment.</p>
<p>Xcel Global Services markets all the products and educates all clients about the opportunities without any external pressure to have decided on this service/product etc.</p>
<p>The client has noticed all the above provisions in detail, agrees, and continues to adhere to all the terms and conditions of signing/acknowledging this agreement.</p>
<p>Xcel Global Services is operated and controlled in India with its registered office at Hyderabad, Telangana. The laws of the Government of India and the State Government of Telangana will govern the validity, interpretation, and performance of this Agreement. The courts in Hyderabad, Telangana alone shall have jurisdiction to try any dispute between the company and any person arising out of any issue concerning the company.</p>
<p>Force Majeure. In no event shall the Company be responsible or liable for any failure or delay in the performance of its obligations hereunder arising out of or caused by, directly or indirectly, forces beyond its control, including, without limitation &ndash; strikes, work stoppages, accidents, acts of war or terrorism, civil or military disturbances, nuclear or natural catastrophes or acts of God, any outbreaks, Epidemics or Pandemics; and interruptions, loss or malfunctions of utilities, communications or computer (software and hardware) services. It is understood that the company shall use reasonable efforts to resume service as soon as practicable under the circumstances. Your file will be withheld /deferred until the situations are under control. If we found you ineligible to apply, no refund will be due on service fee paid as service has already been initiated.</p>
<p>Charge Back: It is agreed by the client that she/he knows that Xcel Global Services will deploy its employees and utilize other infrastructures for providing services to the client by spending considerable amounts of money. Irrespective of the result of the request, the client hereby undertakes that he will not claim a refund of the fees and charges paid to Xcel Global Services, except to the extent provided in the agreement.</p>
<p>The client hereby agrees and understands the deliverables of the service signed up for, and hence will not initiate a chargeback (applicable only for Card Payments).</p>
<p>For further details, please Reach out to us on +91 93433 69999 or you can e-mail us on&nbsp;<a href="mailto:kukatpally@xcelgs.com"><strong>kukatpally@xcelgs.com</strong></a>. One of our representatives will get back to you at the earliest.</p>
            </div>
          </Col>
        </Row>
      </Container>
    </div>
  );
};

export default RefundPolicy;